/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tiendaelectrica.menus.menuproveedores;

import com.tiendaelectrica.menus.menuprincipal.menuprincipal;

/**
 *
 * @author camper
 */
public class menuproveedores extends javax.swing.JFrame {

    /**
     * Creates new form menuproveedores
     */
    public menuproveedores() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        registrarproveedor = new javax.swing.JButton();
        editarproveedor = new javax.swing.JButton();
        buscarproveedor = new javax.swing.JButton();
        eliminarproveedor = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("MENU PROVEEDORES");

        registrarproveedor.setBackground(new java.awt.Color(204, 255, 255));
        registrarproveedor.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        registrarproveedor.setText("Registrar Proveedor");
        registrarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarproveedorActionPerformed(evt);
            }
        });

        editarproveedor.setBackground(new java.awt.Color(204, 255, 255));
        editarproveedor.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        editarproveedor.setText("Editar Proveedor");
        editarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarproveedorActionPerformed(evt);
            }
        });

        buscarproveedor.setBackground(new java.awt.Color(204, 255, 255));
        buscarproveedor.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        buscarproveedor.setText("Buscar Proveedor");
        buscarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarproveedorActionPerformed(evt);
            }
        });

        eliminarproveedor.setBackground(new java.awt.Color(204, 255, 255));
        eliminarproveedor.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        eliminarproveedor.setText("Eliminar Proveedor");
        eliminarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarproveedorActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(255, 204, 204));
        regresar.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        regresar.setText("Regresar al Menu Principal");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registrarproveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(registrarproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regresar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarproveedorActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DEL INVENTARIO
    }//GEN-LAST:event_registrarproveedorActionPerformed

    private void editarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarproveedorActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DE CLIENTES
    }//GEN-LAST:event_editarproveedorActionPerformed

    private void buscarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarproveedorActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DEL VENTAS
    }//GEN-LAST:event_buscarproveedorActionPerformed

    private void eliminarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarproveedorActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DE COMPRAS
    }//GEN-LAST:event_eliminarproveedorActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
        menuprincipal menu = new menuprincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuproveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuproveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuproveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuproveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuproveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarproveedor;
    private javax.swing.JButton editarproveedor;
    private javax.swing.JButton eliminarproveedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarproveedor;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
