/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tiendaelectrica.menureportes;

import com.tiendaelectrica.menuprincipal.menuprincipal;

/**
 *
 * @author camper
 */
public class menureportes extends javax.swing.JFrame {

    /**
     * Creates new form menureportes
     */
    public menureportes() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        reportesventas = new javax.swing.JButton();
        reportesclientes = new javax.swing.JButton();
        reportesproductos = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("MENU REPORTES");

        reportesventas.setBackground(new java.awt.Color(204, 255, 255));
        reportesventas.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        reportesventas.setText("Reportes Ventas");
        reportesventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesventasActionPerformed(evt);
            }
        });

        reportesclientes.setBackground(new java.awt.Color(204, 255, 255));
        reportesclientes.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        reportesclientes.setText("Reportes Clientes");
        reportesclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesclientesActionPerformed(evt);
            }
        });

        reportesproductos.setBackground(new java.awt.Color(204, 255, 255));
        reportesproductos.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        reportesproductos.setText("Reportes Productos");
        reportesproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesproductosActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(255, 204, 204));
        regresar.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        regresar.setText("Regresar al Menu Principal");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportesproductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportesclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportesventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addComponent(reportesventas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportesclientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reportesproductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regresar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportesventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesventasActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DEL INVENTARIO
    }//GEN-LAST:event_reportesventasActionPerformed

    private void reportesclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesclientesActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DE CLIENTES
    }//GEN-LAST:event_reportesclientesActionPerformed

    private void reportesproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesproductosActionPerformed
        // AQUI VA EL CODIGO Y LO LOGICO DE LA PARTE DEL VENTAS
    }//GEN-LAST:event_reportesproductosActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
        menuprincipal menu = new menuprincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menureportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menureportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menureportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menureportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menureportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton regresar;
    private javax.swing.JButton reportesclientes;
    private javax.swing.JButton reportesproductos;
    private javax.swing.JButton reportesventas;
    // End of variables declaration//GEN-END:variables
}
