/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tiendaelectrica.menuprincipal;

//importaciones para la generacion de facturas
import com.tiendaelectrica.factura.domain.service.FacturaService;
import com.tiendaelectrica.factura.infrastructure.in.FacturaController;
import com.tiendaelectrica.factura.infrastructure.out.FacturaRepository;

//importacion para el menu de edicion
import com.tiendaelectrica.forms.menuedicion;

//importaciones para el historial de ventas
import com.tiendaelectrica.historialventas.infrastructure.in.HistorialVentasController;
import com.tiendaelectrica.historialventas.infrastructure.out.HistorialVentasRepository;
import com.tiendaelectrica.historialventas.domain.service.HistorialVentasService;

//importaciones para los pedidos pendientes
import com.tiendaelectrica.pedidospendientes.infrastructure.in.PedidosPendientesController;
import com.tiendaelectrica.pedidospendientes.infrastructure.out.PedidosPendientesRepository;

//importaciones para los reportes
import com.tiendaelectrica.reportes.domain.service.ReportesService;
import com.tiendaelectrica.reportes.infrastructure.in.ReportesController;
import com.tiendaelectrica.reportes.infrastructure.out.ReporteRepository;

/**
 *
 * @author camper
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        facturas = new javax.swing.JButton();
        historialventas = new javax.swing.JButton();
        pedidospendientes = new javax.swing.JButton();
        reportes = new javax.swing.JButton();
        modificacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setFont(new java.awt.Font("Bell MT", 3, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 153, 153));
        Titulo.setText("Tienda Electrica");

        facturas.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        facturas.setForeground(new java.awt.Color(0, 153, 153));
        facturas.setText("Generar Facturas");
        facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturasActionPerformed(evt);
            }
        });

        historialventas.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        historialventas.setForeground(new java.awt.Color(0, 153, 153));
        historialventas.setText("Historial de Ventas");
        historialventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialventasActionPerformed(evt);
            }
        });

        pedidospendientes.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        pedidospendientes.setForeground(new java.awt.Color(0, 153, 153));
        pedidospendientes.setText("Pedidos Pendientes");
        pedidospendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidospendientesActionPerformed(evt);
            }
        });

        reportes.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        reportes.setForeground(new java.awt.Color(0, 153, 153));
        reportes.setText("Reportes");
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });

        modificacion.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        modificacion.setForeground(new java.awt.Color(0, 153, 153));
        modificacion.setText("Modificacion de Datos");
        modificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(modificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(historialventas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facturas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidospendientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(facturas)
                .addGap(18, 18, 18)
                .addComponent(historialventas)
                .addGap(18, 18, 18)
                .addComponent(pedidospendientes)
                .addGap(18, 18, 18)
                .addComponent(reportes)
                .addGap(18, 18, 18)
                .addComponent(modificacion)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificacionActionPerformed
        this.dispose();
        menuedicion MenuEdicion = new menuedicion();
        MenuEdicion.setVisible(true);
    }//GEN-LAST:event_modificacionActionPerformed

    private void historialventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialventasActionPerformed
        HistorialVentasService historialVentasService = new HistorialVentasRepository();
        HistorialVentasController historialVentasController = new HistorialVentasController(historialVentasService);
        historialVentasController.tabla_Historial_ventas();
    }//GEN-LAST:event_historialventasActionPerformed

    private void facturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturasActionPerformed
        FacturaService facturaService = new FacturaRepository();
        FacturaController facturaController = new FacturaController(facturaService);
        facturaController.tabla_factura();
    }//GEN-LAST:event_facturasActionPerformed

    private void pedidospendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidospendientesActionPerformed
        PedidosPendientesRepository pedidosPendientesRepository = new PedidosPendientesRepository();
        PedidosPendientesController pedidosPendientesController = new PedidosPendientesController(pedidosPendientesRepository);
        pedidosPendientesController.tabla_PedidosPendientes();
    }//GEN-LAST:event_pedidospendientesActionPerformed

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
        ReportesService reportesService = new ReporteRepository();
        ReportesController reportesController = new ReportesController(reportesService);
        reportesController.tabla_Reporte();
    }//GEN-LAST:event_reportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton facturas;
    private javax.swing.JButton historialventas;
    private javax.swing.JButton modificacion;
    private javax.swing.JButton pedidospendientes;
    private javax.swing.JButton reportes;
    // End of variables declaration//GEN-END:variables
}
