/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tiendaelectrica.forms;

/**
 *
 * @author camper
 */
public class menuedicion extends javax.swing.JFrame {

    /**
     * Creates new form menuedicion
     */
    public menuedicion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        categorias = new javax.swing.JButton();
        proveedores = new javax.swing.JButton();
        ciudad = new javax.swing.JButton();
        bodega = new javax.swing.JButton();
        detallesventa = new javax.swing.JButton();
        sucursal = new javax.swing.JButton();
        paises = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        compra = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        pedidos = new javax.swing.JButton();
        direccioncliente = new javax.swing.JButton();
        productos = new javax.swing.JButton();
        detallescompra = new javax.swing.JButton();
        ventas = new javax.swing.JButton();
        detallespedidos = new javax.swing.JButton();
        productosproveedores = new javax.swing.JButton();
        regresarmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Modo de Edicion Avanzado");

        categorias.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        categorias.setForeground(new java.awt.Color(0, 153, 153));
        categorias.setText("Categorias");

        proveedores.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        proveedores.setForeground(new java.awt.Color(0, 153, 153));
        proveedores.setText("Proveedores");

        ciudad.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        ciudad.setForeground(new java.awt.Color(0, 153, 153));
        ciudad.setText("Ciudad");

        bodega.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        bodega.setForeground(new java.awt.Color(0, 153, 153));
        bodega.setText("Bodega");

        detallesventa.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        detallesventa.setForeground(new java.awt.Color(0, 153, 153));
        detallesventa.setText("Detalles de Venta");

        sucursal.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        sucursal.setForeground(new java.awt.Color(0, 153, 153));
        sucursal.setText("Sucursal");

        paises.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        paises.setForeground(new java.awt.Color(0, 153, 153));
        paises.setText("Paises");

        clientes.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        clientes.setForeground(new java.awt.Color(0, 153, 153));
        clientes.setText("Clientes");

        compra.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        compra.setForeground(new java.awt.Color(0, 153, 153));
        compra.setText("Compra");

        inventario.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        inventario.setForeground(new java.awt.Color(0, 153, 153));
        inventario.setText("inventario");

        pedidos.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        pedidos.setForeground(new java.awt.Color(0, 153, 153));
        pedidos.setText("Pedidos");

        direccioncliente.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        direccioncliente.setForeground(new java.awt.Color(0, 153, 153));
        direccioncliente.setText("Direccion del Cliente");

        productos.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        productos.setForeground(new java.awt.Color(0, 153, 153));
        productos.setText("Productos");

        detallescompra.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        detallescompra.setForeground(new java.awt.Color(0, 153, 153));
        detallescompra.setText("Detalles de compra");

        ventas.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        ventas.setForeground(new java.awt.Color(0, 153, 153));
        ventas.setText("Ventas");

        detallespedidos.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        detallespedidos.setForeground(new java.awt.Color(0, 153, 153));
        detallespedidos.setText("Detalles de Pedidos");

        productosproveedores.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        productosproveedores.setForeground(new java.awt.Color(0, 153, 153));
        productosproveedores.setText("Productos Proveedores");

        regresarmenu.setFont(new java.awt.Font("Liberation Sans", 2, 24)); // NOI18N
        regresarmenu.setForeground(new java.awt.Color(153, 0, 51));
        regresarmenu.setText("Menu Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(detallespedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detallesventa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detallescompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productosproveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proveedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresarmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bodega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccioncliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detallespedidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(compra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detallescompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ventas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detallesventa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ciudad)
                                .addGap(138, 138, 138))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bodega)
                                .addGap(12, 12, 12)
                                .addComponent(paises)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sucursal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(direccioncliente))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(productosproveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(productos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inventario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regresarmenu)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuedicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuedicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuedicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuedicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuedicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bodega;
    private javax.swing.JButton categorias;
    private javax.swing.JButton ciudad;
    private javax.swing.JButton clientes;
    private javax.swing.JButton compra;
    private javax.swing.JButton detallescompra;
    private javax.swing.JButton detallespedidos;
    private javax.swing.JButton detallesventa;
    private javax.swing.JButton direccioncliente;
    private javax.swing.JButton inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton paises;
    private javax.swing.JButton pedidos;
    private javax.swing.JButton productos;
    private javax.swing.JButton productosproveedores;
    private javax.swing.JButton proveedores;
    private javax.swing.JButton regresarmenu;
    private javax.swing.JButton sucursal;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
