/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tiendaelectrica.forms;
import com.tiendaelectrica.menuprincipal.menuprincipal;

// IMPORTACIONES PARA FUNCIONAR
import com.tiendaelectrica.cruds.compras.CompraDAO;
import main.java.com.tiendaelectrica.cruds.compras.DetallesCompraDAO;

/**
 *
 * @author camper
 */
public class menucompras extends javax.swing.JFrame {

    /**
     * Creates new form menucompras
     */
    public menucompras() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        eliminarcompra = new javax.swing.JButton();
        buscarcompra = new javax.swing.JButton();
        editarcompra = new javax.swing.JButton();
        registrarcompra = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        agregardetallescompra = new javax.swing.JButton();
        buscardetallescompra = new javax.swing.JButton();
        editardetallescompra = new javax.swing.JButton();
        eliminardetallescompra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresar.setBackground(new java.awt.Color(255, 204, 204));
        regresar.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        regresar.setText("Regresar al Menu Principal");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        eliminarcompra.setBackground(new java.awt.Color(204, 255, 255));
        eliminarcompra.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        eliminarcompra.setText("Eliminar Compra");
        eliminarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcompraActionPerformed(evt);
            }
        });

        buscarcompra.setBackground(new java.awt.Color(204, 255, 255));
        buscarcompra.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        buscarcompra.setText("Buscar Compra");
        buscarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarcompraActionPerformed(evt);
            }
        });

        editarcompra.setBackground(new java.awt.Color(204, 255, 255));
        editarcompra.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        editarcompra.setText("Editar Compra");
        editarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarcompraActionPerformed(evt);
            }
        });

        registrarcompra.setBackground(new java.awt.Color(204, 255, 255));
        registrarcompra.setFont(new java.awt.Font("aakar", 2, 24)); // NOI18N
        registrarcompra.setText("Registrar Compra");
        registrarcompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarcompraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("MENU COMPRAS");

        agregardetallescompra.setBackground(new java.awt.Color(204, 255, 255));
        agregardetallescompra.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        agregardetallescompra.setText("Agregar detalles de compra");
        agregardetallescompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregardetallescompraActionPerformed(evt);
            }
        });

        buscardetallescompra.setBackground(new java.awt.Color(204, 255, 255));
        buscardetallescompra.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        buscardetallescompra.setText("Buscar detalles de compra");
        buscardetallescompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscardetallescompraActionPerformed(evt);
            }
        });

        editardetallescompra.setBackground(new java.awt.Color(204, 255, 255));
        editardetallescompra.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        editardetallescompra.setText("Editar detalles de compra");
        editardetallescompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editardetallescompraActionPerformed(evt);
            }
        });

        eliminardetallescompra.setBackground(new java.awt.Color(204, 255, 255));
        eliminardetallescompra.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        eliminardetallescompra.setText("Eliminar detalles de compra");
        eliminardetallescompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminardetallescompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buscarcompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarcompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarcompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registrarcompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminardetallescompra, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editardetallescompra, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscardetallescompra, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregardetallescompra, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarcompra)
                    .addComponent(agregardetallescompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarcompra)
                    .addComponent(buscardetallescompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarcompra)
                    .addComponent(editardetallescompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarcompra)
                    .addComponent(eliminardetallescompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regresar)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    CompraDAO compraDAO = new CompraDAO();
    DetallesCompraDAO detallesCompraDAO = new DetallesCompraDAO();

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
        menuprincipal menu = new menuprincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void eliminarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcompraActionPerformed
        compraDAO.eliminarCompra();
    }//GEN-LAST:event_eliminarcompraActionPerformed

    private void buscarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarcompraActionPerformed
        compraDAO.obtenerCompra();
    }//GEN-LAST:event_buscarcompraActionPerformed

    private void editarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarcompraActionPerformed
        compraDAO.actualizarCompra();
    }//GEN-LAST:event_editarcompraActionPerformed

    private void registrarcompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarcompraActionPerformed
        compraDAO.agregarCompra();
    }//GEN-LAST:event_registrarcompraActionPerformed

    private void agregardetallescompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregardetallescompraActionPerformed
        detallesCompraDAO.agregarDetallesCompra();
    }//GEN-LAST:event_agregardetallescompraActionPerformed

    private void buscardetallescompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscardetallescompraActionPerformed
        detallesCompraDAO.obtenerDetallesCompra();
    }//GEN-LAST:event_buscardetallescompraActionPerformed

    private void editardetallescompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editardetallescompraActionPerformed
        detallesCompraDAO.actualizarDetallesCompra();
    }//GEN-LAST:event_editardetallescompraActionPerformed

    private void eliminardetallescompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminardetallescompraActionPerformed
        detallesCompraDAO.eliminarDetallesCompra();
    }//GEN-LAST:event_eliminardetallescompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menucompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menucompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menucompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menucompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menucompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregardetallescompra;
    private javax.swing.JButton buscarcompra;
    private javax.swing.JButton buscardetallescompra;
    private javax.swing.JButton editarcompra;
    private javax.swing.JButton editardetallescompra;
    private javax.swing.JButton eliminarcompra;
    private javax.swing.JButton eliminardetallescompra;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registrarcompra;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
